server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service-openapi
          uri: lb://user-service
          predicates:
            - Path=/user-service/v3/api-docs
          filters:
            - RewritePath=/user-service/v3/api-docs, /v3/api-docs

        - id: investment-service-openapi
          uri: lb://investment-service
          predicates:
            - Path=/investment-service/v3/api-docs
          filters:
            - RewritePath=/investment-service/v3/api-docs, /v3/api-docs

        - id: land-service-openapi
          uri: lb://land-service
          predicates:
            - Path=/land-service/v3/api-docs
          filters:
            - RewritePath=/land-service/v3/api-docs, /v3/api-docs

        - id: user-service-auth
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - AuthenticationFilter

        - id: investment-service
          uri: lb://investment-service
          predicates:
            - Path=/api/investments/**
          filters:
            - AuthenticationFilter

        - id: land-service
          uri: lb://land-service
          predicates:
            - Path=/api/lands/**
          filters:
            - AuthenticationFilter

      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: User Service
        url: /user-service/v3/api-docs
      - name: Investment Service
        url: /investment-service/v3/api-docs
      - name: Land Service
        url: /land-service/v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.services.gateway: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
